name: CI
on: [ push ]
env:
  TEST_DSN: ""
  TEST_DB_USER: ""
  TEST_DB_PASS: ""
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install composer
      - name: Install migrations
      - name: Run tests