name: CI
on: [ push ]
env:
  TEST_DB_DSN: "mysql:host=mysql;dbname=dpl_db"
  TEST_DB_USER: "root"
  TEST_DB_PASS: "password"

jobs:
  composer:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: "dpl_db"
          MYSQL_ROOT_PASSWORD: "password"
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: imagick