name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [ closed ]
    branches:
      - master
env:
  TEST_DB_DSN: "mysql:host=127.0.0.1;dbname=dpl;port=33306"
  TEST_DB_USER: "root"
  TEST_DB_PASS: "password"
  MYSQL_HOST: 127.0.0.1
  MYSQL_DATABASE: "dpl"
  MYSQL_USER: dpl
  MYSQL_PASSWORD: dpl
  MYSQL_ROOT_PASSWORD: "password"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output base_ref
        run: echo ${{github.event_name}} ${{ toJson(github.event) }}
