name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [ closed ]
    branches:
      - master
env:
  TEST_DB_DSN: "mysql:host=127.0.0.1;dbname=dpl;port=33306"
  TEST_DB_USER: "root"
  TEST_DB_PASS: "password"
  MYSQL_HOST: 127.0.0.1
  MYSQL_DATABASE: "dpl"
  MYSQL_USER: dpl
  MYSQL_PASSWORD: dpl
  MYSQL_ROOT_PASSWORD: "password"

jobs:
  build:
    if: github.event.pull_request.merged == true || (github.event.ref == 'refs/heads/master' || github.event_name == 'push')
    runs-on: ubuntu-latest
    steps:
      - name: Output base_ref
        run: | 
          echo 
          echo '1' ${{ toJson(github.event.pull_request) }} ${{ github.event.pull_request }} 
          echo '2' ${{ github.event_name }} ${{ github.event.push.ref }} 
          echo '3' ${{ github.event.push }} ${{ toJson(github.event.push) }}
          echo '33' ${{ github.event.ref }} ${{ github.event_name }}
          echo '4' ${{ toJson(github.event) }}
